# -*- coding: utf-8 -*-
"""TASK 1—Credit Scoring Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nEokGos1f8Om3olOGkyr_QqL37oh175t

# ================================================================
#   CodeAlpha Machine Learning Internship
#   TASK 1 — Credit Scoring Model
#   Developer  : Muhammad Ali
#   Dataset    : German Credit Risk Dataset
#   Models     : Logistic Regression · Decision Tree
#                Random Forest · XGBoost
#   Platform   : Google Colab
#   Libraries  : Scikit-learn · XGBoost · Imbalanced-learn · Gradio
#
#   What this project does:
#   Takes a person's financial data (age, income, credit history etc.)
#   and predicts whether they are a GOOD or BAD credit risk.
#   Helps banks decide whether to approve or reject a loan.
# ==================================================

# ────────────────────────────────────────────────────────────────
# CELL 1 — Install Libraries
#
# ⚠️  Only install what Colab does NOT already have.
#     Do NOT reinstall tensorflow, gradio, numpy — already there.
# ───────────────────────────────────────────────────
"""

!pip install -q imbalanced-learn xgboost scikit-learn \
              matplotlib seaborn pandas

"""
# ────────────────────────────────────────────────────────────────
# CELL 2 — Imports + Configuration
# ──────────────────────────────────────────────────────"""

import pandas            as pd
import numpy             as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn           as sns
import warnings
import os
import time

warnings.filterwarnings('ignore')

# ── Scikit-learn ──────────────────────────────────────────────
from sklearn.model_selection   import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing     import StandardScaler, LabelEncoder
from sklearn.linear_model      import LogisticRegression
from sklearn.tree              import DecisionTreeClassifier
from sklearn.ensemble          import RandomForestClassifier
from sklearn.metrics           import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, roc_curve,
    classification_report, confusion_matrix,
    average_precision_score
)

# ── XGBoost ───────────────────────────────────────────────────
from xgboost import XGBClassifier

# ── Imbalanced-learn (SMOTE) ──────────────────────────────────
from imblearn.over_sampling import SMOTE

# ── Gradio ────────────────────────────────────────────────────
import gradio as gr

# ── Reproducibility ───────────────────────────────────────────
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

# ── Constants ─────────────────────────────────────────────────
TEST_SIZE  = 0.20
MODEL_PATH = '/tmp/best_credit_model.pkl'

# ── Color palette ─────────────────────────────────────────────
PALETTE = {
    'good'    : '#10B981',   # green  → good credit
    'bad'     : '#EF4444',   # red    → bad credit
    'primary' : '#6366F1',   # indigo
    'warning' : '#F59E0B',   # amber
    'info'    : '#0EA5E9',   # sky blue
    'purple'  : '#8B5CF6',
}
MODEL_COLORS = ['#6366F1', '#10B981', '#F59E0B', '#EF4444']

print("=" * 55)
print("  CodeAlpha — Task 1: Credit Scoring Model")
print("=" * 55)
print(f"  Pandas       : {pd.__version__}")
print(f"  Scikit-learn : loaded ✅")
print(f"  XGBoost      : loaded ✅")
print(f"  Imbalanced   : loaded ✅  (SMOTE ready)")
print(f"  Gradio       : {gr.__version__}")
print("=" * 55)

"""
# ────────────────────────────────────────────────────────────────
# CELL 3 — Load German Credit Risk Dataset
#
# Dataset: German Credit Risk (Kaggle / UCI version)
# 1,000 applicants · 9 features · Binary target (good / bad)
#
# Features:
#   Age              — applicant age in years
#   Sex              — male / female
#   Job              — 0=unskilled, 1=skilled, 2=highly skilled
#   Housing          — own / free / rent
#   Saving accounts  — little / moderate / quite rich / rich
#   Checking account — little / moderate / rich
#   Credit amount    — loan amount in DM (Deutsche Mark)
#   Duration         — loan duration in months
#   Purpose          — car / furniture / education / business / etc.
#   Risk             — TARGET: good (0) or bad (1) credit risk
# ─────────────────────────────────────────────────────"""

def load_credit_dataset():
    """
    Loads the German Credit Risk dataset.
    Tries 2 reliable online sources, then falls back
    to a synthetic dataset if both fail.
    """
    print("📥  Loading German Credit Risk dataset...")

    # ── Source 1 ──────────────────────────────────────────────
    url1 = ("https://raw.githubusercontent.com/"
             "dsrscientist/dataset1/master/german_credit_risk.csv")
    # ── Source 2 ──────────────────────────────────────────────
    url2 = ("https://raw.githubusercontent.com/"
             "YBIFoundation/Dataset/main/Credit%20Risk.csv")

    for attempt, url in enumerate([url1, url2], 1):
        try:
            df = pd.read_csv(url)
            print(f"   ✅  Loaded from source {attempt}")
            return df
        except Exception as e:
            print(f"   ⚠️   Source {attempt} failed: {e}")

    # ── Fallback: synthetic dataset ───────────────────────────
    print("   📊  Creating synthetic dataset as fallback...")
    return _make_synthetic_dataset()


def _make_synthetic_dataset():
    """
    Generates a realistic synthetic credit dataset (1,000 rows)
    when all online sources are unavailable.
    Column names intentionally match the German Credit Risk format.
    """
    np.random.seed(RANDOM_STATE)
    n = 1000

    age       = np.random.randint(18, 75, n)
    sex       = np.random.choice(['male', 'female'], n)
    job       = np.random.choice([0, 1, 2, 3], n,
                                  p=[0.05, 0.20, 0.63, 0.12])
    housing   = np.random.choice(['own', 'free', 'rent'], n,
                                  p=[0.71, 0.11, 0.18])
    saving    = np.random.choice(
                    ['little', 'moderate', 'quite rich', 'rich', np.nan],
                    n, p=[0.60, 0.10, 0.10, 0.06, 0.14])
    checking  = np.random.choice(
                    ['little', 'moderate', 'rich', np.nan],
                    n, p=[0.27, 0.27, 0.06, 0.40])
    credit_amt= np.random.randint(250, 18424, n)
    duration  = np.random.choice(
                    [6, 12, 18, 24, 30, 36, 48, 60, 72], n)
    purpose   = np.random.choice(
                    ['car', 'furniture/equipment', 'radio/TV',
                     'domestic appliances', 'repairs', 'education',
                     'business', 'vacation/others'], n)

    # Risk: bad risk linked to higher amount + shorter history
    risk_prob = (0.3
                 + 0.2 * (credit_amt > 5000)
                 + 0.15 * (duration > 24)
                 - 0.1  * (job >= 2)
                 - 0.1  * (age > 35))
    risk_prob = np.clip(risk_prob, 0.05, 0.95)
    risk      = np.where(
                    np.random.random(n) < risk_prob,
                    'bad', 'good')

    df = pd.DataFrame({
        'Age'             : age,
        'Sex'             : sex,
        'Job'             : job,
        'Housing'         : housing,
        'Saving accounts' : saving,
        'Checking account': checking,
        'Credit amount'   : credit_amt,
        'Duration'        : duration,
        'Purpose'         : purpose,
        'Risk'            : risk,
    })
    return df


# ── Load ──────────────────────────────────────────────────────
df_raw = load_credit_dataset()

# ── Standardise column names (strip spaces, lower) ───────────
df_raw.columns = (df_raw.columns
                  .str.strip()
                  .str.lower()
                  .str.replace(' ', '_'))

# ── Confirm we have a usable target column ────────────────────
# Common names: 'risk', 'class', 'credit_risk', 'target'
target_candidates = ['risk', 'class', 'credit_risk', 'target', 'creditability']
TARGET_COL = next(
    (c for c in target_candidates if c in df_raw.columns),
    df_raw.columns[-1]   # last column as last resort
)

print(f"\n   Target column   : '{TARGET_COL}'")
print(f"   Unique values   : {df_raw[TARGET_COL].unique()}")
print(f"   Shape           : {df_raw.shape}")
print(f"\n   First 3 rows:")
print(df_raw.head(3).to_string())

"""
# ────────────────────────────────────────────────────────────────
# CELL 4 — Exploratory Data Analysis (EDA)
#
# Before building any model, we must UNDERSTAND the data.
# Check data types, missing values, class balance, statistics.
# ────────────────────────────────────────────────────"""

print("\n" + "═" * 55)
print("  EXPLORATORY DATA ANALYSIS")
print("═" * 55)

print("\n📋  Data types:")
print(df_raw.dtypes.to_string())

print("\n📋  Missing values per column:")
missing = df_raw.isnull().sum()
if missing.sum() == 0:
    print("   ✅  No missing values found!")
else:
    print(missing[missing > 0].to_string())
    print(f"   Total missing : {missing.sum()}")

print("\n📋  Basic statistics (numerical columns):")
print(df_raw.describe().round(2).to_string())

# ── Class distribution ────────────────────────────────────────
target_counts = df_raw[TARGET_COL].value_counts()
total         = len(df_raw)
print(f"\n📊  Class Distribution:")
for cls, cnt in target_counts.items():
    print(f"   {str(cls):>12}  :  {cnt}  ({cnt/total*100:.1f}%)")

"""
# ────────────────────────────────────────────────────────────────
# CELL 5 — Visualize the Data
#
# 6 charts:
#   A. Credit risk class distribution
#   B. Age distribution by risk
#   C. Credit amount by risk (box plot)
#   D. Loan duration by risk
#   E. Purpose of loan breakdown
#   F. Missing values heatmap
# ──────────────────────────────────────────────────"""

fig = plt.figure(figsize=(20, 14))
fig.suptitle(
    'Credit Risk Dataset — Exploratory Data Analysis',
    fontsize=16, fontweight='bold', y=0.99
)
gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.42, wspace=0.35)

# Ensure target is string for easy comparison
target_series = df_raw[TARGET_COL].astype(str).str.lower()

# ── A: Class distribution ─────────────────────────────────────
ax1 = fig.add_subplot(gs[0, 0])
counts = target_series.value_counts()
bar_colors = [PALETTE['good'] if 'good' in k else PALETTE['bad']
              for k in counts.index]
bars = ax1.bar(counts.index, counts.values,
               color=bar_colors, width=0.5,
               edgecolor='white', linewidth=1.5)
for bar, cnt in zip(bars, counts.values):
    ax1.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 5,
             f'{cnt}\n({cnt/total*100:.0f}%)',
             ha='center', fontweight='bold', fontsize=11)
ax1.set_title('Credit Risk Distribution',
              fontweight='bold', fontsize=12)
ax1.set_ylabel('Number of Applicants')
ax1.spines[['top', 'right']].set_visible(False)
ax1.set_ylim(0, counts.max() * 1.25)

# ── B: Age distribution by risk ───────────────────────────────
ax2 = fig.add_subplot(gs[0, 1])
if 'age' in df_raw.columns:
    for risk_val, color, lbl in [
        ('good', PALETTE['good'], 'Good Risk'),
        ('bad',  PALETTE['bad'],  'Bad Risk'),
    ]:
        ages = df_raw[target_series == risk_val]['age'].dropna()
        ax2.hist(ages, bins=20, alpha=0.65,
                 color=color, label=lbl, edgecolor='white')
    ax2.legend(fontsize=9)
    ax2.set_xlabel('Age (years)')
    ax2.set_ylabel('Count')
else:
    ax2.text(0.5, 0.5, 'Age column\nnot found',
             ha='center', va='center', transform=ax2.transAxes)
ax2.set_title('Age Distribution by Risk', fontweight='bold', fontsize=12)
ax2.spines[['top', 'right']].set_visible(False)

# ── C: Credit amount by risk ──────────────────────────────────
ax3 = fig.add_subplot(gs[0, 2])
amt_col = next(
    (c for c in df_raw.columns if 'credit' in c and 'amount' in c),
    next((c for c in df_raw.columns if 'amount' in c), None)
)
if amt_col:
    good_amt = df_raw[target_series == 'good'][amt_col].dropna()
    bad_amt  = df_raw[target_series == 'bad'][amt_col].dropna()
    ax3.boxplot(
        [good_amt, bad_amt],
        labels=['Good Risk', 'Bad Risk'],
        patch_artist=True,
        boxprops={'facecolor': PALETTE['info'], 'alpha': 0.5},
        medianprops={'color': PALETTE['bad'], 'linewidth': 2.5}
    )
    ax3.set_ylabel('Credit Amount')
else:
    ax3.text(0.5, 0.5, 'Amount column\nnot found',
             ha='center', va='center', transform=ax3.transAxes)
ax3.set_title('Credit Amount by Risk', fontweight='bold', fontsize=12)
ax3.spines[['top', 'right']].set_visible(False)

# ── D: Duration by risk ───────────────────────────────────────
ax4 = fig.add_subplot(gs[1, 0])
dur_col = next(
    (c for c in df_raw.columns if 'duration' in c), None
)
if dur_col:
    good_dur = df_raw[target_series == 'good'][dur_col].dropna()
    bad_dur  = df_raw[target_series == 'bad'][dur_col].dropna()
    ax4.boxplot(
        [good_dur, bad_dur],
        labels=['Good Risk', 'Bad Risk'],
        patch_artist=True,
        boxprops={'facecolor': PALETTE['warning'], 'alpha': 0.5},
        medianprops={'color': PALETTE['primary'], 'linewidth': 2.5}
    )
    ax4.set_ylabel('Duration (months)')
else:
    ax4.text(0.5, 0.5, 'Duration column\nnot found',
             ha='center', va='center', transform=ax4.transAxes)
ax4.set_title('Loan Duration by Risk', fontweight='bold', fontsize=12)
ax4.spines[['top', 'right']].set_visible(False)

# ── E: Purpose breakdown ──────────────────────────────────────
ax5 = fig.add_subplot(gs[1, 1])
purpose_col = next(
    (c for c in df_raw.columns if 'purpose' in c), None
)
if purpose_col:
    purpose_counts = df_raw[purpose_col].value_counts()
    short_labels   = [str(x)[:12] for x in purpose_counts.index]
    ax5.barh(short_labels, purpose_counts.values,
             color=PALETTE['purple'], alpha=0.75, edgecolor='white')
    ax5.set_xlabel('Count')
else:
    ax5.text(0.5, 0.5, 'Purpose column\nnot found',
             ha='center', va='center', transform=ax5.transAxes)
ax5.set_title('Loan Purpose Breakdown', fontweight='bold', fontsize=12)
ax5.spines[['top', 'right']].set_visible(False)

# ── F: Risk vs Housing ────────────────────────────────────────
ax6 = fig.add_subplot(gs[1, 2])
housing_col = next(
    (c for c in df_raw.columns if 'housing' in c), None
)
if housing_col:
    ct = pd.crosstab(df_raw[housing_col],
                     target_series,
                     normalize='index') * 100
    ct.plot(kind='bar', ax=ax6,
            color=[PALETTE['good'], PALETTE['bad']],
            edgecolor='white', width=0.6)
    ax6.set_xlabel('Housing Type')
    ax6.set_ylabel('Percentage (%)')
    ax6.tick_params(axis='x', rotation=20)
    ax6.legend(['Good Risk', 'Bad Risk'], fontsize=9)
else:
    ax6.text(0.5, 0.5, 'Housing column\nnot found',
             ha='center', va='center', transform=ax6.transAxes)
ax6.set_title('Risk % by Housing Type', fontweight='bold', fontsize=12)
ax6.spines[['top', 'right']].set_visible(False)

plt.savefig('/tmp/credit_eda.png', dpi=120,
            bbox_inches='tight', facecolor='white')
plt.show()
print("✅  EDA charts saved → /tmp/credit_eda.png")

"""
# ────────────────────────────────────────────────────────────────
# CELL 6 — Preprocess the Data
#
# Steps:
#   1. Encode target as 0 (good) / 1 (bad)
#   2. Fill missing values in categorical columns with 'unknown'
#   3. Fill missing values in numerical columns with median
#   4. Label-encode all categorical features
#   5. Feature engineering — create useful derived features
# ───────────────────────────────────────────────────"""

print("\n🔧  Preprocessing data...")

df = df_raw.copy()

# ── Step 1: Encode target → 0=Good, 1=Bad ────────────────────
target_raw = df[TARGET_COL].astype(str).str.lower().str.strip()

if target_raw.isin(['good', 'bad']).all():
    # String labels → 0/1
    y = (target_raw == 'bad').astype(int)
elif target_raw.isin(['1', '2']).all():
    # UCI format: 1=Good → 0, 2=Bad → 1
    y = (target_raw == '2').astype(int)
else:
    # Unknown format — use LabelEncoder
    le_target = LabelEncoder()
    y = pd.Series(le_target.fit_transform(target_raw))
    print(f"   Target encoded: {dict(zip(le_target.classes_, le_target.transform(le_target.classes_)))}")

df = df.drop(columns=[TARGET_COL])

print(f"   Target 0 (Good credit) : {(y==0).sum()}")
print(f"   Target 1 (Bad credit)  : {(y==1).sum()}")

# ── Step 2: Separate column types ────────────────────────────
cat_cols = df.select_dtypes(include=['object']).columns.tolist()
num_cols = df.select_dtypes(include=[np.number]).columns.tolist()

print(f"\n   Categorical columns ({len(cat_cols)}) : {cat_cols}")
print(f"   Numerical columns  ({len(num_cols)}) : {num_cols}")

# ── Step 3: Fill missing values ───────────────────────────────
missing_total = df.isnull().sum().sum()
if missing_total > 0:
    print(f"\n   Filling {missing_total} missing values...")
    for col in cat_cols:
        df[col] = df[col].fillna('unknown')
    for col in num_cols:
        df[col] = df[col].fillna(df[col].median())
    print("   ✅  Missing values handled!")
else:
    print("\n   ✅  No missing values to handle")

# ── Step 4: Encode categorical columns ───────────────────────
le_dict = {}
for col in cat_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    le_dict[col] = le
print(f"\n   ✅  {len(cat_cols)} categorical columns encoded")

# ── Step 5: Feature engineering ──────────────────────────────
# Create new informative features from existing ones

# Debt-to-duration ratio: higher = riskier
if amt_col and dur_col:
    df['amount_per_month'] = (
        df[amt_col] / df[dur_col].replace(0, 1)
    )
    print("   ✅  Feature created: amount_per_month")

# Age group: young borrowers may be higher risk
if 'age' in df.columns:
    df['age_group'] = pd.cut(
        df['age'],
        bins    = [0, 25, 35, 50, 100],
        labels  = [0, 1, 2, 3]          # young/adult/mature/senior
    ).astype(float).fillna(1)
    print("   ✅  Feature created: age_group")

# Update column lists after engineering
FEATURE_NAMES = list(df.columns)
X             = df.copy()

print(f"\n   Final feature count : {len(FEATURE_NAMES)}")
print(f"   X shape             : {X.shape}")
print(f"   y shape             : {y.shape}")
print("\n  ✅  Preprocessing complete!")

"""
# ────────────────────────────────────────────────────────────────
# CELL 7 — Handle Class Imbalance with SMOTE
#
# Problem:
#   If dataset has 700 "good" and 300 "bad", the model will learn
#   to always predict "good" to get 70% accuracy — but that misses
#   ALL the risky applicants!
#
# Fix (SMOTE):
#   Synthetic Minority Over-sampling Technique creates artificial
#   "bad" examples that look realistic until both classes are equal.
#   This forces the model to actually learn the risky patterns.
# ──────────────────────────────────────────────────"""

print("\n⚖️   Handling class imbalance...")
print(f"   Before SMOTE → Good: {(y==0).sum()}, Bad: {(y==1).sum()}")

X_arr = X.values.astype(float)
y_arr = y.values

try:
    smote        = SMOTE(random_state=RANDOM_STATE, k_neighbors=5)
    X_balanced, y_balanced = smote.fit_resample(X_arr, y_arr)

    print(f"   After  SMOTE → Good: {(y_balanced==0).sum()}, "
          f"Bad: {(y_balanced==1).sum()}")
    print("   ✅  Classes balanced with SMOTE!")
except Exception as e:
    print(f"   ⚠️   SMOTE failed ({e}) — using original data with class_weight")
    X_balanced = X_arr
    y_balanced = y_arr

X_balanced = pd.DataFrame(X_balanced, columns=FEATURE_NAMES)
y_balanced = pd.Series(y_balanced)

"""
# ────────────────────────────────────────────────────────────────
# CELL 8 — Split Train / Test + Scale Features
#
# We split BEFORE scaling to prevent data leakage.
# (If we scaled the whole dataset, test data would "contaminate"
#  the scaler — giving unrealistically good evaluation results.)
#
# Rule: FIT scaler on train only → APPLY on both train and test.
# ─────────────────────────────────────────────────────"""

X_train, X_test, y_train, y_test = train_test_split(
    X_balanced, y_balanced,
    test_size    = TEST_SIZE,
    random_state = RANDOM_STATE,
    stratify     = y_balanced
)

# StandardScaler: make mean=0, std=1 for each feature
scaler         = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)    # fit + transform
X_test_scaled  = scaler.transform(X_test)          # transform only

print(f"\n📊  Data Split:")
print(f"   Training set : {X_train.shape[0]} rows "
      f"(Good: {(y_train==0).sum()}, Bad: {(y_train==1).sum()})")
print(f"   Test set     : {X_test.shape[0]} rows "
      f"(Good: {(y_test==0).sum()}, Bad: {(y_test==1).sum()})")
print(f"\n  ✅  Train / Test split complete!")

"""
# ────────────────────────────────────────────────────────────────
# CELL 9 — Train 4 Machine Learning Models
#
# We train four different algorithms and compare.
# Each has a different strategy for finding the decision boundary.
#
#   Logistic Regression → finds a straight-line boundary
#   Decision Tree       → builds an if/else rule tree
#   Random Forest       → 200 decision trees, majority vote
#   XGBoost            → trees that correct each other's errors
# ────────────────────────────────────────────────────"""

print("\n🚀  Training 4 machine learning models...\n")

models = {
    'Logistic Regression': LogisticRegression(
        C            = 1.0,
        max_iter     = 1000,
        random_state = RANDOM_STATE,
        class_weight = 'balanced'
    ),
    'Decision Tree': DecisionTreeClassifier(
        max_depth        = 6,
        min_samples_split= 10,
        random_state     = RANDOM_STATE,
        class_weight     = 'balanced'
    ),
    'Random Forest': RandomForestClassifier(
        n_estimators = 200,
        max_depth    = 8,
        random_state = RANDOM_STATE,
        class_weight = 'balanced',
        n_jobs       = -1
    ),
    'XGBoost': XGBClassifier(
        n_estimators  = 200,
        max_depth     = 4,
        learning_rate = 0.1,
        random_state  = RANDOM_STATE,
        eval_metric   = 'logloss',
        verbosity     = 0,
        scale_pos_weight = (y_train==0).sum() / (y_train==1).sum()
    ),
}

results        = {}
trained_models = {}

for name, model in models.items():
    print(f"  ▶  Training  {name:<25}", end="  ")
    t0 = time.time()

    # Logistic Regression + SVM need scaled data
    needs_scale = name in ['Logistic Regression']
    Xtr = X_train_scaled if needs_scale else X_train.values
    Xte = X_test_scaled  if needs_scale else X_test.values

    model.fit(Xtr, y_train)

    y_pred = model.predict(Xte)
    y_prob = model.predict_proba(Xte)[:, 1]

    # Metrics
    acc  = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, zero_division=0)
    rec  = recall_score(y_test, y_pred, zero_division=0)
    f1   = f1_score(y_test, y_pred, zero_division=0)
    auc  = roc_auc_score(y_test, y_prob)

    elapsed = time.time() - t0
    print(f"done {elapsed:.1f}s  |  Acc: {acc:.3f}  "
          f"F1: {f1:.3f}  AUC: {auc:.3f}")

    results[name] = {
        'accuracy'   : acc,
        'precision'  : prec,
        'recall'     : rec,
        'f1_score'   : f1,
        'roc_auc'    : auc,
        'y_pred'     : y_pred,
        'y_prob'     : y_prob,
    }
    trained_models[name] = model

print("\n  ✅  All 4 models trained!")

"""

# ────────────────────────────────────────────────────────────────
# CELL 10 — Compare All Models (Bar Chart)
# ──────────────────────────────────────────────────────"""

model_names   = list(results.keys())
metrics_keys  = ['accuracy', 'precision', 'recall', 'f1_score', 'roc_auc']
metrics_labels= ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC-AUC']

fig, axes = plt.subplots(1, 5, figsize=(22, 6))
fig.suptitle('Credit Scoring — Model Performance Comparison',
             fontsize=15, fontweight='bold', y=1.02)

for i, (mkey, mlabel) in enumerate(zip(metrics_keys, metrics_labels)):
    ax     = axes[i]
    values = [results[m][mkey] for m in model_names]
    bars   = ax.bar(
        range(len(model_names)), values,
        color=MODEL_COLORS, edgecolor='white', width=0.62
    )
    # Value labels
    for bar, val in zip(bars, values):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 0.006,
            f'{val:.3f}',
            ha='center', fontsize=9, fontweight='bold'
        )

    ax.set_title(mlabel, fontweight='bold', fontsize=12)
    ax.set_xticks(range(len(model_names)))
    ax.set_xticklabels(['LR', 'DT', 'RF', 'XGB'], fontsize=10)
    ax.set_ylim(0.4, 1.08)
    ax.set_ylabel('Score')
    ax.spines[['top', 'right']].set_visible(False)
    ax.grid(axis='y', alpha=0.22, linestyle='--')

    # Gold border on best bar
    best_idx = int(np.argmax(values))
    bars[best_idx].set_edgecolor('#FFD700')
    bars[best_idx].set_linewidth(3)

# Legend
legend_patches = [
    plt.Rectangle((0, 0), 1, 1, color=MODEL_COLORS[i],
                  label=model_names[i])
    for i in range(len(model_names))
]
fig.legend(handles=legend_patches, loc='lower center',
           ncol=4, bbox_to_anchor=(0.5, -0.10), fontsize=10)

plt.tight_layout()
plt.savefig('/tmp/model_comparison.png', dpi=120,
            bbox_inches='tight', facecolor='white')
plt.show()

# ── Summary table ─────────────────────────────────────────────
print("\n📊  Model Comparison Table:")
print(f"{'Model':<22} {'Acc':>7} {'Prec':>7} "
      f"{'Recall':>8} {'F1':>7} {'AUC':>7}")
print("─" * 60)
for name in model_names:
    r = results[name]
    print(f"{name:<22} "
          f"{r['accuracy']:>7.3f} "
          f"{r['precision']:>7.3f} "
          f"{r['recall']:>8.3f} "
          f"{r['f1_score']:>7.3f} "
          f"{r['roc_auc']:>7.3f}")

# Select best model
BEST_MODEL_NAME = max(results, key=lambda m: results[m]['roc_auc'])
best_model      = trained_models[BEST_MODEL_NAME]
print(f"\n  🏆  Best model : {BEST_MODEL_NAME}  "
      f"(AUC = {results[BEST_MODEL_NAME]['roc_auc']:.3f})")

"""
# ────────────────────────────────────────────────────────────────
# CELL 11 — ROC-AUC Curves
#
# Shows how well each model distinguishes good vs bad credit risk.
# AUC = 1.0 → perfect | AUC = 0.5 → no better than random guessing
# ───────────────────────────────────────────────────"""

fig, ax = plt.subplots(figsize=(9, 7))

for i, name in enumerate(model_names):
    fpr, tpr, _ = roc_curve(y_test, results[name]['y_prob'])
    auc_val      = results[name]['roc_auc']
    is_best      = (name == BEST_MODEL_NAME)

    ax.plot(
        fpr, tpr,
        color     = MODEL_COLORS[i],
        linewidth = 3.0 if is_best else 1.8,
        linestyle = '-'  if is_best else '--',
        label     = f"{name}  (AUC = {auc_val:.3f})"
                    + ("  🏆" if is_best else "")
    )

# Random baseline
ax.plot([0, 1], [0, 1], 'k--', linewidth=1,
        alpha=0.5, label='Random (AUC = 0.500)')
ax.fill_between([0, 1], [0, 1], alpha=0.04, color='gray')

ax.set_xlabel('False Positive Rate (Good customer flagged as Bad)',
              fontsize=11)
ax.set_ylabel('True Positive Rate (Bad customer correctly found)',
              fontsize=11)
ax.set_title('ROC-AUC Curves — Credit Scoring Models\n'
             '(Closer to top-left corner = better)',
             fontsize=13, fontweight='bold')
ax.legend(loc='lower right', fontsize=10)
ax.grid(True, alpha=0.18, linestyle='--')
ax.spines[['top', 'right']].set_visible(False)
ax.set_xlim([-0.01, 1.01])
ax.set_ylim([-0.01, 1.01])

plt.tight_layout()
plt.savefig('/tmp/roc_curves.png', dpi=120,
            bbox_inches='tight', facecolor='white')
plt.show()
print("✅  ROC curves saved → /tmp/roc_curves.png")

"""
# ────────────────────────────────────────────────────────────────
# CELL 12 — Feature Importance
#
# Which financial factors matter most in predicting credit risk?
# Random Forest and XGBoost can rank every feature by importance.
# ─────────────────────────────────────────────────────"""

tree_models = {
    k: v for k, v in trained_models.items()
    if hasattr(v, 'feature_importances_')
}

if tree_models:
    n_plots = len(tree_models)
    fig, axes = plt.subplots(1, n_plots, figsize=(10 * n_plots, 8))
    if n_plots == 1:
        axes = [axes]

    fig.suptitle('Feature Importance — Which Financial Factors Matter Most?',
                 fontsize=14, fontweight='bold')

    for ax, (mname, mmodel), color in zip(
        axes, tree_models.items(),
        [PALETTE['primary'], PALETTE['warning']]
    ):
        importances = mmodel.feature_importances_
        indices     = np.argsort(importances)
        feat_labels = [FEATURE_NAMES[i] for i in indices]

        bars = ax.barh(
            range(len(indices)), importances[indices],
            color=color, alpha=0.82, edgecolor='white'
        )
        for bar, val in zip(bars, importances[indices]):
            ax.text(
                bar.get_width() + 0.001,
                bar.get_y() + bar.get_height() / 2,
                f'{val:.3f}', va='center', fontsize=9
            )

        ax.set_yticks(range(len(indices)))
        ax.set_yticklabels(feat_labels, fontsize=10)
        ax.set_xlabel('Importance Score', fontsize=11)
        ax.set_title(mname, fontweight='bold', fontsize=13)
        ax.spines[['top', 'right']].set_visible(False)
        ax.grid(axis='x', alpha=0.18, linestyle='--')

    plt.tight_layout()
    plt.savefig('/tmp/feature_importance.png', dpi=120,
                bbox_inches='tight', facecolor='white')
    plt.show()

    # Top 5 features
    rf_imp = trained_models.get('Random Forest')
    if rf_imp:
        top5 = np.argsort(rf_imp.feature_importances_)[::-1][:5]
        print("  🔑  Top 5 features (Random Forest):")
        for rank, idx in enumerate(top5, 1):
            print(f"      {rank}. {FEATURE_NAMES[idx]:<22} "
                  f": {rf_imp.feature_importances_[idx]:.3f}")
else:
    print("  ⚠️   No tree-based models available for importance plot.")

"""
# ────────────────────────────────────────────────────────────────
# CELL 13 — Best Model Deep Evaluation + Confusion Matrix
# ────────────────────────────────────────────────────"""

print(f"\n📊  Deep evaluation — {BEST_MODEL_NAME}")
print("─" * 55)

best_y_pred = results[BEST_MODEL_NAME]['y_pred']
best_y_prob = results[BEST_MODEL_NAME]['y_prob']

print("\nClassification Report:")
print(classification_report(
    y_test, best_y_pred,
    target_names=['Good Credit (0)', 'Bad Credit (1)']
))

# 5-fold cross-validation
print("  5-Fold Cross-Validation:")
needs_scale_cv = (BEST_MODEL_NAME == 'Logistic Regression')
X_cv  = pd.DataFrame(scaler.transform(X_balanced),
                     columns=FEATURE_NAMES) \
         if needs_scale_cv else X_balanced
cv    = StratifiedKFold(n_splits=5, shuffle=True,
                         random_state=RANDOM_STATE)
cv_sc = cross_val_score(best_model, X_cv, y_balanced,
                          cv=cv, scoring='roc_auc')
print(f"  AUC scores : {cv_sc.round(3)}")
print(f"  Mean AUC   : {cv_sc.mean():.3f} ± {cv_sc.std():.3f}")

# ── Confusion matrix ──────────────────────────────────────────
cm = confusion_matrix(y_test, best_y_pred)
tn, fp, fn, tp = cm.ravel()

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle(f'Best Model Evaluation: {BEST_MODEL_NAME}',
             fontsize=14, fontweight='bold')

sns.heatmap(
    cm, annot=True, fmt='d', cmap='Blues', ax=ax1,
    xticklabels=['Good Credit', 'Bad Credit'],
    yticklabels=['Good Credit', 'Bad Credit'],
    linewidths=1.5, linecolor='white',
    annot_kws={'size': 18, 'weight': 'bold'}
)
ax1.set_xlabel('Predicted', fontsize=12)
ax1.set_ylabel('Actual',    fontsize=12)
ax1.set_title(
    f'Confusion Matrix\n'
    f'Accuracy: {results[BEST_MODEL_NAME]["accuracy"]*100:.1f}%',
    fontweight='bold', fontsize=12
)

# Metrics horizontal bar
metric_vals = [
    results[BEST_MODEL_NAME]['accuracy'],
    results[BEST_MODEL_NAME]['precision'],
    results[BEST_MODEL_NAME]['recall'],
    results[BEST_MODEL_NAME]['f1_score'],
    results[BEST_MODEL_NAME]['roc_auc'],
]
metric_lbl = ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC-AUC']
bar_colors = [PALETTE['primary'], PALETTE['good'],
              PALETTE['warning'], PALETTE['info'], PALETTE['purple']]

bars = ax2.barh(metric_lbl, metric_vals,
                color=bar_colors, edgecolor='white', height=0.5)
for bar, val in zip(bars, metric_vals):
    ax2.text(
        bar.get_width() + 0.004,
        bar.get_y() + bar.get_height() / 2,
        f'{val:.3f}', va='center', fontweight='bold', fontsize=11
    )
ax2.set_xlim(0, 1.12)
ax2.set_title(f'All Metrics — {BEST_MODEL_NAME}',
              fontweight='bold', fontsize=12)
ax2.spines[['top', 'right']].set_visible(False)
ax2.grid(axis='x', alpha=0.18, linestyle='--')

plt.tight_layout()
plt.savefig('/tmp/best_model_eval.png', dpi=120,
            bbox_inches='tight', facecolor='white')
plt.show()

print(f"\n  ✅  True  Positives (Bad caught correctly) : {tp}")
print(f"  ✅  True  Negatives (Good approved rightly) : {tn}")
print(f"  ⚠️   False Positives (Good wrongly rejected): {fp}")
print(f"  ⚠️   False Negatives (Bad wrongly approved) : {fn}")
print("\n  ✅  Best model evaluation complete!")

"""
# ────────────────────────────────────────────────────────────────
# CELL 14 — Build Gradio UI
#
# Tabs:
#   1. Credit Risk Check — enter applicant details → get risk score
#   2. Model Comparison  — all 4 models + metrics table
#   3. Feature Importance — what matters most
#   4. Data Analysis     — EDA charts
#   5. How It Works      — plain-English explanation
# ──────────────────────────────────────────────────"""

def predict_credit_risk(*input_values):
    """
    Takes applicant financial inputs from Gradio sliders
    and returns a credit risk prediction.

    Returns:
        result_text (str)  — verdict + confidence
        probs_dict  (dict) — probability bar chart data
    """
    try:
        # Build input array in feature order
        values = np.array(input_values, dtype=float).reshape(1, -1)
        values = pd.DataFrame(values, columns=FEATURE_NAMES)

        # Scale if needed
        if BEST_MODEL_NAME == 'Logistic Regression':
            values_input = scaler.transform(values)
        else:
            values_input = values.values

        proba      = best_model.predict_proba(values_input)[0]
        pred       = int(np.argmax(proba))
        bad_prob   = float(proba[1])
        good_prob  = float(proba[0])

        # Risk tier
        if bad_prob < 0.30:
            tier = "🟢 LOW RISK"
        elif bad_prob < 0.60:
            tier = "🟡 MEDIUM RISK"
        else:
            tier = "🔴 HIGH RISK"

        verdict = "✅ Good Credit — Loan Likely Approved" \
                  if pred == 0 else \
                  "⚠️ Bad Credit — Loan Likely Rejected"

        result_text = (
            f"{tier}\n\n"
            f"{verdict}\n\n"
            f"Good Credit Probability : {good_prob*100:.1f}%\n"
            f"Bad  Credit Probability : {bad_prob*100:.1f}%\n\n"
            f"Model used : {BEST_MODEL_NAME}\n\n"
            f"⚠️  This is an AI prediction for educational "
            f"purposes only.\n"
            f"Actual loan decisions involve more factors."
        )

        probs = {
            'Good Credit (Approve)': round(good_prob, 4),
            'Bad Credit (Reject)  ': round(bad_prob,  4),
        }
        return result_text, probs

    except Exception as e:
        return f"❌ Error: {str(e)}", {}


def build_app():

    with gr.Blocks(
        title = "Credit Scoring — CodeAlpha ML Task 1",
        theme = gr.themes.Soft(primary_hue="indigo")
    ) as demo:

        # ── Header ────────────────────────────────────────────
        gr.Markdown(f"""
        # 💳 Credit Scoring Model
        **CodeAlpha ML Internship — Task 1** |
        Developer: **Muhammad Ali**

        > German Credit Risk Dataset · 4 ML Models ·
        > Best: **{BEST_MODEL_NAME}** (AUC = {results[BEST_MODEL_NAME]['roc_auc']:.3f})
        """)

        with gr.Tabs():

            # ══ TAB 1: PREDICT ════════════════════════════════
            with gr.TabItem("💳 Credit Risk Check"):
                gr.Markdown("""
                ### Enter Applicant Financial Details
                Adjust the sliders to match the applicant's profile,
                then click **Assess Credit Risk**.
                """)

                # Build input sliders from feature list
                input_components = []

                with gr.Row():
                    with gr.Column():
                        gr.Markdown("#### 👤 Personal Details")
                        for feat in FEATURE_NAMES[:len(FEATURE_NAMES)//2]:
                            mn  = float(X_balanced[feat].min())
                            mx  = float(X_balanced[feat].max())
                            med = float(X_balanced[feat].median())
                            stp = 1.0 if (mx - mn) > 5 else 0.1

                            comp = gr.Slider(
                                minimum = mn,
                                maximum = mx,
                                value   = med,
                                step    = stp,
                                label   = feat.replace('_', ' ').title()
                            )
                            input_components.append(comp)

                    with gr.Column():
                        gr.Markdown("#### 💰 Financial Details")
                        for feat in FEATURE_NAMES[len(FEATURE_NAMES)//2:]:
                            mn  = float(X_balanced[feat].min())
                            mx  = float(X_balanced[feat].max())
                            med = float(X_balanced[feat].median())
                            stp = 1.0 if (mx - mn) > 5 else 0.1

                            comp = gr.Slider(
                                minimum = mn,
                                maximum = mx,
                                value   = med,
                                step    = stp,
                                label   = feat.replace('_', ' ').title()
                            )
                            input_components.append(comp)

                predict_btn = gr.Button(
                    "🔍 Assess Credit Risk",
                    variant = "primary",
                    size    = "lg"
                )

                with gr.Row():
                    result_box   = gr.Textbox(
                        label    = "📋 Credit Assessment",
                        lines    = 9,
                        max_lines= 12
                    )
                    result_chart = gr.Label(
                        label           = "📊 Risk Probabilities",
                        num_top_classes = 2
                    )

                # Example profiles
                gr.Markdown("### 💡 Example Applicant Profiles")
                examples = []
                for _, row in X_balanced.head(6).iterrows():
                    examples.append([float(row[f]) for f in FEATURE_NAMES])

                gr.Examples(
                    examples = examples,
                    inputs   = input_components,
                    label    = "Click to load an example profile"
                )

                predict_btn.click(
                    fn      = predict_credit_risk,
                    inputs  = input_components,
                    outputs = [result_box, result_chart]
                )

            # ══ TAB 2: MODEL COMPARISON ═══════════════════════
            with gr.TabItem("📊 Model Comparison"):
                gr.Markdown(f"""
                ### All 4 Models — Head to Head
                **Winner: {BEST_MODEL_NAME}** |
                AUC: {results[BEST_MODEL_NAME]['roc_auc']:.3f} |
                Accuracy: {results[BEST_MODEL_NAME]['accuracy']:.3f}
                """)
                with gr.Row():
                    gr.Image('/tmp/model_comparison.png',
                             label="Metric Comparison")
                    gr.Image('/tmp/roc_curves.png',
                             label="ROC-AUC Curves")

                # Results table in markdown
                table = ("| Model | Accuracy | Precision | "
                         "Recall | F1 | AUC |\n"
                         "|-------|----------|-----------|"
                         "--------|-----|-----|\n")
                for name in model_names:
                    r    = results[name]
                    star = " 🏆" if name == BEST_MODEL_NAME else ""
                    table += (f"| **{name}{star}** | "
                              f"{r['accuracy']:.3f} | "
                              f"{r['precision']:.3f} | "
                              f"{r['recall']:.3f} | "
                              f"{r['f1_score']:.3f} | "
                              f"{r['roc_auc']:.3f} |\n")
                gr.Markdown(table)

            # ══ TAB 3: FEATURE IMPORTANCE ═════════════════════
            with gr.TabItem("🔑 Feature Importance"):
                gr.Markdown("""
                ### Which Financial Factors Predict Credit Risk Most?
                Longer bar = stronger influence on the prediction.
                """)
                with gr.Row():
                    if os.path.exists('/tmp/feature_importance.png'):
                        gr.Image('/tmp/feature_importance.png',
                                 label="Feature Importance")
                    gr.Image('/tmp/best_model_eval.png',
                             label="Best Model — Confusion Matrix")

            # ══ TAB 4: DATA ANALYSIS ══════════════════════════
            with gr.TabItem("📈 Data Analysis"):
                gr.Markdown("### German Credit Risk Dataset — EDA")
                gr.Image('/tmp/credit_eda.png',
                         label="Exploratory Data Analysis")
                gr.Markdown(f"""
### Dataset Summary

| Property | Value |
|----------|-------|
| Total applicants | **{len(df_raw)}** |
| Features | **{X.shape[1]}** |
| Good credit | **{(y==0).sum()} ({(y==0).sum()/len(y)*100:.1f}%)** |
| Bad credit | **{(y==1).sum()} ({(y==1).sum()/len(y)*100:.1f}%)** |
| SMOTE applied | **Yes — balanced classes** |
| Training samples | **{len(X_train)}** |
| Test samples | **{len(X_test)}** |
| Source | **German Credit Risk (UCI / Kaggle)** |
                """)

            # ══ TAB 5: HOW IT WORKS ════════════════════════════
            with gr.TabItem("⚙️ How It Works"):
                gr.Markdown("""
## How Credit Scoring Works

### Step 1 — Collect Financial Data
The model uses 9+ features about an applicant:
age, housing, savings, checking account, loan amount, duration, purpose, and more.

### Step 2 — Handle Class Imbalance (SMOTE)
```python
# Real datasets often have more "good" than "bad" customers.
# SMOTE creates synthetic "bad" examples to balance classes.
smote = SMOTE(random_state=42)
X_balanced, y_balanced = smote.fit_resample(X, y)
# Before: 700 good, 300 bad
# After : 700 good, 700 bad  ← model learns both equally
```

### Step 3 — Normalize Features
```python
# Loan amount (10,000) and age (35) are very different scales.
# StandardScaler brings them to the same scale.
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_train)
```

### Step 4 — Train 4 Models, Pick the Best
```
Logistic Regression → straight decision boundary
Decision Tree       → if/else rules (interpretable)
Random Forest       → 200 trees vote together
XGBoost             → trees fix each other's errors
```

### Step 5 — Predict Risk
```python
proba = model.predict_proba(applicant_data)
# → [0.78, 0.22] means 78% Good Credit, 22% Bad Credit
# → Approve the loan!
```

### Key Metrics Explained
| Metric | What it means for credit scoring |
|--------|----------------------------------|
| Precision | When we predict "bad" — how often are we right? |
| Recall | Out of all actual bad customers — how many did we catch? |
| F1-Score | Balance between precision and recall |
| ROC-AUC | Overall ability to rank good vs bad (1.0 = perfect) |

> ⚠️ In credit scoring, **Recall is critical**.
> Missing a bad customer (False Negative) is expensive for banks.
                """)

    return demo

"""
# ────────────────────────────────────────────────────────────────
# CELL 15 — Launch
# ────────────────────────────────────────────────────"""

print(f"\n🚀  Launching Credit Scoring app...")
print(f"   Developer    : Muhammad Ali")
print(f"   Best model   : {BEST_MODEL_NAME}")
print(f"   Best AUC     : {results[BEST_MODEL_NAME]['roc_auc']:.3f}")
print(f"   Best Accuracy: {results[BEST_MODEL_NAME]['accuracy']:.3f}")
print(f"   Features     : {len(FEATURE_NAMES)}")
print(f"   Dataset size : {len(df_raw)} applicants\n")

app = build_app()
app.launch(share=True, debug=False, show_error=True, quiet=True)

"""# ===============================================
#  TESTING CHECKLIST:
#  ✅ Load example applicant → click Assess Credit Risk
#  ✅ Adjust credit amount slider → see probability change
#  ✅ Model Comparison tab → full metrics table
#  ✅ Feature Importance tab → which factors matter most
#  ✅ Data Analysis tab → EDA visualizations
#  ✅ How It Works tab → plain-English explanation
#
#  EXPECTED RESULTS:
#  ✅ Best AUC      : 0.85 – 0.93
#  ✅ Best Accuracy : 0.80 – 0.88
#  ✅ Training time : < 45 seconds (all 4 models)
#  ✅ CV AUC        : 0.82 – 0.90
#
#  GITHUB REPO NAME:
#  CodeAlpha_CreditScoring
# ===============================================
"""